### ISSUE TITLE
Updating the number of watched episodes

### ISSUE THREAD

**Issue by m4tx** [SuperMarcus/myanimelist-api-specification#1]
I found an issue regarding this section: https://github.com/SuperMarcus/myanimelist-api-specification#update-entries. It says:

> The request parameters can be one of the entries in the MyListStatusObject

This is, however, not exactly true. When sending `num_episodes_watched` field, the server returns an error:

```
{"message":"This form should not contain extra fields.","error":"bad_request"}
```

The field should be in fact called `num_episodes_watched` when making a PUT/PATCH request. The response will still contain `num_watched_episodes`. Like so:

```
RequestBuilder {
    method: PATCH,
    url: "https://api.myanimelist.net/v2/anime/918/my_list_status",
    headers: {
        "authorization": "Bearer ...",
        "content-type": "application/x-www-form-urlencoded",
    },
}
num_watched_episodes=1

Response: {"status":"on_hold","score":0,"num_episodes_watched":1,"is_rewatching":false,"updated_at":"2020-04-17T20:47:36+00:00","priority":0,"num_times_rewatched":0,"rewatch_value":0,"tags":[],"comments":""}
```

**Comment by m0mosenpai** [comment]
I came across the same issue that @m4tx reported. Changing to `num_watched_episodes` in PUT/PATCH request makes it work

**Comment by SuperMarcus** [comment]
I apologize for taking the time to reply. You guys are absolutely correct. In fact, I am using the `num_watched_episodes` for mutation requests in my own app but forgot to document it here.

Anyways, thanks for letting me know. I'll update the documents to reflect that.
